---

# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: password

# SMTP settings.
smtp_host: smtp.gmail.com
smtp_user: admin@example.com
smtp_password: mypassword


# Application settings.
django_settings_file: housing_survey.settings
django_secret_key: akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#

run_django_syncdb: yes
run_django_south_migration: yes
run_django_collectstatic: yes
