---
- name: install mysql-server
  action: apt name=mysql-server
  notify:
    - mysql_secure_installation

- name: write conf.d/mysqld.cnf
  action: template src=mysqld.cnf.j2 dest=/etc/mysql/conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: write conf.d/client.cnf
  action: template src=client.cnf.j2 dest=/etc/mysql/conf.d/client.cnf
  notify:
    - restart mysql

- name: create mysql user ahs
  mysql_user: name=ahs password=12345 priv=*.*:ALL state=present

- name: create mysql database
  mysql_db: name=housing_survey login_user=ahs login_password=12345
