---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Create Django migrations
  raw: cd {{ virtualenv_path }}; source bin/activate; cd {{ project_path }}; python manage.py makemigrations

- name: Run Django migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_south_migration
  tags: django.migrate

- name: Create Django admin
  raw: cd {{ virtualenv_path }}; source bin/activate; cd {{ project_path }}; python manage.py loaddata data/initial/initial_data.json

- name: Create Django admin session
  raw: cd {{ virtualenv_path }}; source bin/activate; cd {{ project_path }}; python manage.py loaddata data/initial/initial_sessions.json
