---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - libffi-dev
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - libmysqlclient-dev
    - supervisor
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Ssl libraries 1
  pip: name=requests[security] version=2.5.3

- name: Install mysqldb module
  apt: pkg=python-mysqldb state=installed

- name: Intall mysql-python module
  pip: name=MySQL-python
